model_config:
  task: state_prediction

  glm_tokenizer_path: pretrained_models/glm-4-voice-tokenizer
  model_name: pretrained_models/Qwen3-0.6B-expand_vocab_v2
  llm_dim: 1024
  lm_vocab_size: 151936

  enable_lora: true
  lora_r: 32
  lora_alpha: 64

  # enable_cascade_asr: false

  # init_ckpt_path: 
  # init_ckpt_path_lora: 

infer_config:
  seed: 42
  device: cuda
  precision: bf16
  max_wait_num: 5
  max_mistake_num: 5

  input:
    chunk_size: 2560
    audio_back_size: 15360
    audio_ahead_size: 640
    sample_rate: 16000

  asr:
    model_name: sensevoice
    # model_name: paraformer
    language: en
